name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker Image
        run: |
          docker build -t wry0313/personal-website-server:latest .
          docker push wry0313/personal-website-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@18.221.68.221 "
            docker stop \$(docker ps -q --filter 'publish=8080') || true &&
            docker rm \$(docker ps -a -q --filter 'publish=8080') || true &&
            docker pull wry0313/personal-website-server:latest && 
            docker run -d -p 8080:8080 wry0313/personal-website-server:latest
          "

        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
